version: '3.4'
services:
  dockerListener:
    image: node
    ports:
    - 3000:3000
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${PWD}/proxy:/usr/src/app/
    working_dir: /usr/src/app
    command: npm start
